---
- hosts: all
  tasks:
    - name: install interactive packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - findutils
        - less
        - man-db
        - procps
        - which
        - vim-minimal
