---
- hosts: all
  tasks:
    - name: install pip-2.7
      yum:
        name: python27-pip
        state: present
    - name: install supervisor
      pip:
        name: supervisor
        executable: pip-2.7
    - name: make supervisor dirs
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/supervisor
        - /etc/supervisor/programs
        - /var/opt/supervisor
    - name: copy supervisor config
      copy:
        src: files/supervisord.conf
        dest: /etc/supervisor/supervisord.conf
