---
- hosts: all
  tasks:
    - name: uninstall pip-2.7
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - python27-pip
    - name: remove junk
      file:
        name: "{{ item }}"
        state: absent
      with_items:
        - /root/.cache
        - /var/cache
        - /usr/share/doc
