#!/bin/bash
# chkconfig: 345 80 80
# description: it reports state
# pidfile: /var/opt/healthz/healthz.pid

. /etc/init.d/functions

PIDFILE=/var/opt/healthz/healthz.pid

start() {
  echo -n "Starting healthz: "
  if [ -f $PIDFILE ]; then
    PID=`cat $PIDFILE`
    echo healthz already running: $PID
    exit 2;
  else
    /usr/bin/python3.6 /opt/healthz/healthz.py 9002 /var/opt/healthz/state &
    echo $! > $PIDFILE
    echo
    return 0
  fi
}

stop() {
  echo -n "Shutting down healthz: "
  echo
  killproc -p $PIDFILE healthz
  echo
  return 0
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p $PIDFILE
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage:  {start|stop|status|restart}"
    exit 1
    ;;
esac
exit $?
